### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by Rattlyy** [TheGrimSilence/Minecraft-1.12.2-Forge-MDK#1]
Remove this or else the repository will get DMCA'd by Mojang. You are not allowed to share ANY minecraft asset or code.

**Comment by test1230-lab** [comment]
who are you

**Comment by orthocenter** [comment]
This is I assume just the deobfuscated, decompiled files that comes with forge's MCP, but placed in a convenient location. Given that forge is so well known, I doubt Mojang will do anything.

**Comment by Rattlyy** [comment]
> This is I assume just the deobfuscated, decompiled files that comes with forge's MCP, but placed in a convenient location. Given that forge is so well known, I doubt Mojang will do anything.

you cant post mcp outputs on github.

**Comment by orthocenter** [comment]
Really??????

**Comment by TheGrimSilence** [comment]
> Remove this or else the repository will get DMCA'd by Mojang. You are not allowed to share ANY minecraft asset or code.

This repo is almost 2 years old. I made this when I first started off in modding however, you're right. On the other hand, I won't be removing this repo. In compliance, I'll just wipe the history and upload the MDK for easy access as was the intended purpose.
